# ~/.Brewfile
cask_args appdir: '/Applications'
# taps
tap 'homebrew/php'
tap 'jawshooah/pyenv'
tap 'nodenv/nodenv'
cask 'java'
# brews
brew 'autojump'
brew 'composer'
brew 'dnsmasq'
brew 'docker-cloud'
brew 'elixir'
brew 'exercism'
brew 'gist'
brew 'git'
brew 'gsl'
brew 'heroku'
brew 'htop'
brew 'mackup'
brew 'mas'
brew 'mongodb'
brew 'mr'
brew 'mtr'
brew 'nodenv'
brew 'nodenv-default-packages'
brew 'openssl'
brew 'php-code-sniffer'
brew 'postgresql'
brew 'pwgen'
brew 'pyenv'
brew "pyenv-default-packages", args: ["HEAD"]
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'reattach-to-user-namespace'
brew 'rust'
brew 'ssh-copy-id'
brew 'tmux'
brew 'wget'
# casks
cask '1password'
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'atom'
cask 'authy-desktop'
cask 'backblaze'
cask 'chefdk'
cask 'choosy'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'font-hack'
cask 'font-inconsolata'
cask 'font-hack'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'google-hangouts'
cask 'gpgtools'
cask 'hazel'
cask 'istat-menus'
cask 'iterm2'
cask 'java'
cask 'keybase'
cask 'microsoft-office'
cask 'mongohub'
cask 'ngrok'
cask 'nvalt'
cask 'rescuetime'
cask 'sequel-pro'
cask 'sketch'
cask 'skype'
cask 'slack'
cask 'sonos'
cask 'spotify'
cask 'steam'
cask 'synology-cloud-station-drive'
cask 'vagrant'
cask 'virtualbox'
# mac app store
mas 'Day One', id: 1055511498
mas 'Deliveries', id: 924726344
mas 'Keynote', id: 409183694
mas 'Notability', id: 736189492
mas 'Pages', id: 409201541
mas 'Pocket', id: 568494494
mas 'Simplify', id: 448003584
mas 'Todoist', id: 585829637
mas 'Tweetbot', id: 1384080005
mas 'Xcode', id: 497799835
