---
database_file: <%= File.expand_path("~/.timetrap/timetrap.db") %>
round_in_seconds: 900
append_notes_delimiter: ", "
formatter_search_paths:
- <%= File.expand_path("~/.timetrap/formatters") %>
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- <%= File.expand_path("~/.timetrap/auto_sheets") %>
default_command: 
auto_checkout: false
require_note: false
